### ISSUE TITLE
Spanish translation.

### ISSUE THREAD

**Issue by vidimus** [Hobbeslionheart/DowntheAtticHole#1]
Hello, @Hobbeslionheart . I would like to translate this scenario into Spanish. It's simple and I guess it could be useful for new players to see how the game works.

**Comment by vidimus** [comment]
I've already translated the scenario (it's a short one). Any chance for adding the Spanish translation to valkyrie?

**Comment by Hobbeslionheart** [comment]
My first issue! Sure. send the translation. I need to brush up on how to include it.

**Comment by Hobbeslionheart** [comment]
Sorry for the delay in the reply.

**Comment by vidimus** [comment]
No problem.

> My first issue! Sure. send the translation. I need to brush up on how to include it.

I've uploaded the file here:
https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/issues/4

I think you have to edit the quest.ini file to add a line with the new available language. And them just add the file "Localization.Spanish.txt" to your scenario folder (and pack it for valkyrie).

Check this guide created for Valkyrie (pag 177)
[https://docs.google.com/document/d/1Gi5gTwKkw84Px0Lvk-bJ3Aml_vF3ZoljjB6a8FjWGt8/edit](url)

**Comment by Hobbeslionheart** [comment]
Added and published. Thanks!
